/**
 * chronorace-fetcher.mjs
 * Helltrack — race results from ChronoRace, the UCI's on-site timing vendor.
 *
 * ChronoRace is upstream of every other source: the official UCI results PDFs are
 * generated by them (`Producer: chronorace - electronic timing via ABCpdf`), and their
 * report for the Les Gets 2026 Elite Men final was stamped ~40 min after the last rider.
 * Full background + discovery notes in docs/chronorace-api.md.
 *
 * results.chronorace.be is public and self-documented (Swagger at /swagger). The WBD
 * document ("WBD World Series API") is discovery-based, so unlike results-fetcher.mjs
 * this needs no hardcoded race calendar:
 *     discovery/event-list → discovery/competition-list/{eventId} → resource/results/{competitionId}
 *
 * Usage:
 *   node scripts/chronorace-fetcher.mjs --probe            # dump API contract + live discovery
 *   node scripts/chronorace-fetcher.mjs --probe --raw      # …plus raw response bodies
 */

const BASE = 'https://results.chronorace.be'
const WBD  = `${BASE}/api/v1/wbd`
const UA   = 'Mozilla/5.0 (Helltrack results fetcher; helltrack.app)'
const sleep = ms => new Promise(r => setTimeout(r, ms))

async function get(url) {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/json' } })
    const text = await res.text()
    let data = null
    try { data = JSON.parse(text) } catch {}
    return { status: res.status, ct: (res.headers.get('content-type') || '').split(';')[0], text, data }
  } catch (err) {
    return { status: 0, ct: '', text: `ERR ${err.message}`, data: null }
  }
}

// ─── Spec introspection ───────────────────────────────────────────────────────
// Resolve a $ref / inline schema down to a flat list of "prop: type" so we can see the
// exact field names a parser must consume, without dumping a 69KB document into CI logs.
function describeSchema(schema, spec, depth = 0, seen = new Set()) {
  if (!schema || depth > 3) return '…'
  if (schema.$ref) {
    const name = schema.$ref.split('/').pop()
    if (seen.has(name)) return `<${name} (recursive)>`
    seen.add(name)
    const target = spec.components?.schemas?.[name] || spec.definitions?.[name]
    return `${name} { ${describeSchema(target, spec, depth + 1, seen)} }`
  }
  if (schema.type === 'array') return `[ ${describeSchema(schema.items, spec, depth + 1, seen)} ]`
  if (schema.properties) {
    return Object.entries(schema.properties)
      .map(([k, v]) => {
        if (v.$ref || v.type === 'array' || v.properties) return `${k}: ${describeSchema(v, spec, depth + 1, new Set(seen))}`
        return `${k}: ${v.type || '?'}${v.format ? `(${v.format})` : ''}`
      })
      .join(', ')
  }
  return schema.type || '?'
}

function responseSchemaOf(op) {
  const ok = op.responses?.['200'] || op.responses?.default
  return ok?.content?.['application/json']?.schema
      || ok?.content?.['text/json']?.schema
      || ok?.schema
      || null
}

async function probeSpec() {
  console.log('########## WBD SPEC CONTRACT ##########')
  const spec = await get(`${BASE}/swagger/WBD/swagger.json`)
  if (!spec.data) { console.log('could not load spec:', spec.status, spec.text.slice(0, 200)); return null }
  const s = spec.data
  console.log(`title: ${s.info?.title} v${s.info?.version}`)
  console.log(`security schemes: ${JSON.stringify(Object.keys(s.components?.securitySchemes || {}))}`)
  console.log(`global security  : ${JSON.stringify(s.security || 'none')}`)

  const want = [
    '/api/v1/wbd/discovery/event-list',
    '/api/v1/wbd/discovery/competition-list/{eventId}',
    '/api/v1/wbd/discovery/resource-list/{eventId}',
    '/api/v1/wbd/resource/results/{competitionId}',
    '/api/v1/wbd/live/DHI/situation/{competitionId}',
  ]
  for (const p of want) {
    const op = s.paths?.[p]?.get
    console.log(`\n=== GET ${p}`)
    if (!op) { console.log('   (not in spec)'); continue }
    const params = op.parameters || []
    if (!params.length) console.log('   params: (none)')
    for (const prm of params) {
      const t = prm.schema?.type || prm.type || '?'
      const enums = prm.schema?.enum ? ` enum=${JSON.stringify(prm.schema.enum)}` : ''
      console.log(`   param: ${prm.name} in=${prm.in} required=${!!prm.required} type=${t}${enums}`)
    }
    console.log(`   response: ${describeSchema(responseSchemaOf(op), s)}`.slice(0, 1400))
  }
  return s
}

// ─── Live discovery ───────────────────────────────────────────────────────────
async function probeLive(showRaw) {
  console.log('\n\n########## LIVE DISCOVERY ##########')
  const variants = [
    `${WBD}/discovery/event-list`,
    `${WBD}/discovery/event-list?season=2026`,
    `${WBD}/discovery/event-list?season=26`,
    `${WBD}/discovery/event-list?Season=2026`,
  ]
  let events = null
  for (const u of variants) {
    const r = await get(u)
    const n = Array.isArray(r.data) ? r.data.length : (r.data ? 'object' : '-')
    console.log(`  ${String(r.status).padEnd(3)} ${String(r.text.length).padStart(7)}b ${r.ct.padEnd(17)} items=${n}  ${u}`)
    if (showRaw && r.text) console.log(`      raw: ${r.text.slice(0, 600).replace(/\n/g, ' ')}`)
    if (!events && Array.isArray(r.data) && r.data.length) events = r.data
    await sleep(150)
  }
  if (!events) { console.log('\n(no event array resolved — see raw above)'); return }

  console.log(`\n--- ${events.length} events; keys of [0]: ${Object.keys(events[0]).join(', ')}`)
  console.log(`--- events[0]: ${JSON.stringify(events[0]).slice(0, 500)}`)
  console.log('\n--- all events ---')
  for (const e of events) {
    const id = e.Id ?? e.EventId ?? e.eventId ?? e.id
    const nm = e.Name ?? e.EventName ?? e.name ?? ''
    const dt = e.StartDate ?? e.Date ?? e.startDate ?? ''
    console.log(`  ${String(id).padEnd(12)} ${String(dt).slice(0, 10).padEnd(12)} ${nm}`)
  }

  // Val di Sole is the live target (Worlds, finals 2026-08-29).
  const target = events.find(e => /sole/i.test(e.Name ?? e.EventName ?? e.name ?? ''))
             || events.find(e => /gets/i.test(e.Name ?? e.EventName ?? e.name ?? ''))
  if (!target) { console.log('\n(neither Val di Sole nor Les Gets found)'); return }
  const evId = target.Id ?? target.EventId ?? target.eventId ?? target.id
  console.log(`\n>>> target event: ${target.Name ?? target.EventName ?? target.name} (id=${evId})`)

  const comps = await get(`${WBD}/discovery/competition-list/${evId}`)
  const cl = Array.isArray(comps.data) ? comps.data : (comps.data?.Competitions || [])
  console.log(`\n--- competition-list: status=${comps.status} items=${cl.length}`)
  if (showRaw && !cl.length) console.log(`    raw: ${comps.text.slice(0, 600)}`)
  if (cl.length) console.log(`    keys of [0]: ${Object.keys(cl[0]).join(', ')}`)
  for (const c of cl) {
    const id = c.Id ?? c.CompetitionId ?? c.competitionId ?? c.id
    console.log(`  ${String(id).padEnd(14)} ${JSON.stringify(c).slice(0, 260)}`)
  }

  // Pull results for the first competition so we can see the result row shape.
  const first = cl[0]
  if (!first) return
  const cId = first.Id ?? first.CompetitionId ?? first.competitionId ?? first.id
  const res = await get(`${WBD}/resource/results/${cId}`)
  console.log(`\n--- resource/results/${cId}: status=${res.status} len=${res.text.length}`)
  if (res.data) {
    const rows = Array.isArray(res.data) ? res.data : (res.data.Results || res.data.results || [])
    console.log(`    top-level: ${Array.isArray(res.data) ? 'array' : Object.keys(res.data).join(', ')}`)
    console.log(`    rows: ${rows.length}`)
    if (rows[0]) console.log(`    row[0]: ${JSON.stringify(rows[0]).slice(0, 700)}`)
  } else {
    console.log(`    raw: ${res.text.slice(0, 600)}`)
  }
}

const showRaw = process.argv.includes('--raw')
await probeSpec()
await probeLive(showRaw)
console.log('\n########## done ##########')
